### PR TITLE
Fixes the spinny wheel when searching for a filtered prefix that does…

### PR DESCRIPTION
**Pull request by nicko170**
Hey @annikahannig 

The first PR to fix a problem.

Searching for a prefix that is filtered throws a javascript issue. This resolves that. Example of issue: https://lg.ix.asn.au/search/?q=103.10.125.0/24 Note in the JS console it errors out, but the data does come back from the API call.

ARouteServer (which we use heavily) doesn't keep AS paths for dropped routes, and the loopkup function returns a non-mappable default.

This is fixed on my new image here: https://ixau.alicelg.production.internet.asn.au/search?q=103.10.125.0/24 for reference.

### CODE REVIEW

**Comment by nicko170** [comment]
Hey @annikahannig 

I've added my docker changes in now, too.

1. This adds TZDATA to the image, allowing different timezones to work. Without it, go api errors like crazy and wont load routes. 
2. This also improves the docker container tags, which specifically adds a new tag for each branch that's sortable, which means my image update system can detect when changes have been made!  You can read about the theory here: https://fluxcd.io/docs/guides/image-update/ - You can see what the tags look like here: https://github.com/nicko170/alice-lg/pkgs/container/alice-lg

I'll close out #87 now that was opened in error :)

Warm Regards,

**Comment by annikahannig** [comment]
Hej! This is looking pretty good! Thank you!

**Review by annikahannig — APPROVED** [review]

**Comment by nicko170** [comment]
Just saw that build failed on the pull request! 

I'll fix that first thing in the morning, will replace the / with a _ or something :-)

Error: buildx call failed with: error: invalid tag "ghcr.io/alice-lg/alice-lg:88/merge-8fcbb4d-1644325158": invalid reference format

**Comment by annikahannig** [comment]
Yeah I think it has something to do with the merge branch or smth... Worked on main - so I figured this is okay for now

IDK I do no really like github CI. I think gitlab is so much more transparent in what is actually going on there...

**Comment by annikahannig** [comment]
But - since we are here... :woman_shrugging:

**Pull request merged**
